# Generated by Django 4.1.7 on 2023-04-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Category Title')),
                ('slug', models.SlugField(max_length=55, verbose_name='Category Slug')),
                ('vacancy', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(verbose_name='Is Active?')),
                ('is_featured', models.BooleanField(verbose_name='Is Featured?')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='Job', verbose_name='company_logo')),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='Job', verbose_name='company_logo')),
                ('location', models.CharField(max_length=100, null=True)),
                ('job_nature', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('job_description', models.TextField(max_length=250)),
                ('responsibilities', models.TextField(max_length=250)),
                ('qualifications', models.CharField(max_length=250)),
                ('companywebsite', models.CharField(max_length=200)),
                ('companyemail', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('Date_line', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='job Title')),
                ('slug', models.SlugField(max_length=160, verbose_name='job slug')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='Job', verbose_name='company_logo')),
                ('location', models.CharField(max_length=200, null=True)),
                ('job_nature', models.CharField(max_length=200, null=True)),
                ('salary', models.IntegerField()),
                ('Date_line', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
                ('is_featured', models.BooleanField(verbose_name='Is Featured')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.category', verbose_name='job_category')),
            ],
        ),
    ]
