# Generated by Django 4.1.7 on 2023-04-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_company_company_logo_alter_job_date_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='job_title',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.job', verbose_name='job_title'),
        ),
    ]
