# Generated by Django 4.1.7 on 2023-05-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_alter_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
