# Generated by Django 4.1.7 on 2023-05-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_alter_apply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
