# Generated by Django 4.1.7 on 2023-05-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_alter_apply_email_alter_apply_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
