# Generated by Django 4.1.7 on 2023-05-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_alter_apply_address_alter_apply_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='Jobpost', verbose_name='company_logo')),
                ('location', models.CharField(max_length=100, null=True)),
                ('job_nature', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('Date_line', models.CharField(max_length=30)),
            ],
        ),
    ]
