# Generated by Django 4.1.7 on 2023-05-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_nature',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
