# Generated by Django 4.1.7 on 2023-05-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_alter_jobpost_job_nature_alter_jobpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('subject', models.TextField(max_length=200, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
